### Process sgRNA read count and library data
1. for TKOv3, integrate read count data with refined TKOv3 library
2. remove all rows without sgRNA sequences
3. export data in a new format

In [1]:
import pandas as pd

In [17]:
read_count = pd.read_csv("../../data/sgrna_lfc_data/tkov3_data/matrix-reads-by-gRNA-RPE1-drugZ.txt", sep="\t")
read_count['spacer'] = read_count['sgRNA'].str.extract(r'_(.*)$')

col = read_count.pop('spacer')
read_count.insert(1, 'spacer', col)
read_count

,sgRNA,spacer,GENE,RPE1_T0,RPE1_T3A_CTRL_LOPRIMER,RPE1_T3A_CTRL,RPE1_T3A_ENTI_LOPRIMER,RPE1_T3A_ENTI,RPE1_T3A_GEMC,RPE1_T3A_VINC,RPE1_T3B_CTRL,RPE1_T3B_ENTI,RPE1_T3B_GEMC,RPE1_T3B_VINC
0,A1BG_ACTGGCGCCATCGAGAGCCA,ACTGGCGCCATCGAGAGCCA,A1BG,164,83,93,33,50,105,39,44,118,33,77
1,A1BG_CAAGAGAAAGACCACGAGCA,CAAGAGAAAGACCACGAGCA,A1BG,492,416,288,275,262,277,286,222,401,216,228
2,A1BG_GCTCAGCTGGGTCCATCCTG,GCTCAGCTGGGTCCATCCTG,A1BG,258,54,49,38,25,101,28,5,57,52,32
3,A1BG_GTCGAGCTGATTCTGAGCGA,GTCGAGCTGATTCTGAGCGA,A1BG,487,668,360,462,307,353,278,290,565,193,209
4,A1CF_AGTTATGTTAGGTATACCCG,AGTTATGTTAGGTATACCCG,A1CF,149,242,133,193,187,165,133,140,379,87,189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71085,luciferase_GGTCTTCCCGACGATGACGC,GGTCTTCCCGACGATGACGC,luciferase,320,345,160,154,108,150,146,59,167,112,82
71086,luciferase_TATCGATTCCAATTCAGCGG,TATCGATTCCAATTCAGCGG,luciferase,298,265,183,359,339,246,234,153,317,220,195
71087,luciferase_TATTCTGATTACACCCGAGG,TATTCTGATTACACCCGAGG,luciferase,384,603,395,372,361,353,329,243,482,301,345
71088,luciferase_TCTAGAGGATAGAATGGCGC,TCTAGAGGATAGAATGGCGC,luciferase,399,414,266,228,164,244,165,138,418,202,158
71089,luciferase_TTTGTGGACGAAGTACCGAA,TTTGTGGACGAAGTACCGAA,luciferase,392,396,340,196,203,219,203,140,283,262,148

In [19]:
# check that number of unique spacer sequence match with the number of rows
read_count["spacer"].nunique()

71090

In [20]:
library = pd.read_csv("../../data/library_data/refined_library/tkov3_guide_sequence_61K_refined.tsv", sep = "\t", header=None)
library = library.rename(columns={0: "sgRNA", 1: "spacer", 2: "gene"})
library["spacer"]

0        CAAGAGAAAGACCACGAGCA
1        GCTCAGCTGGGTCCATCCTG
2        ACTGGCGCCATCGAGAGCCA
3        GTCGAGCTGATTCTGAGCGA
4        TGCGCTGGACCAGTGCGCGG
                 ...
61019    GACGACGCAGCAGTCGCCGG
61020    AAAGACAACACCCTACAGTG
61021    GTACATATGAGCCCACACAT
61022    ATTGTAGATCACCAGAACAC
61023    TAACAGGTTACAGGGAACAA
Name: spacer, Length: 61024, dtype: object

In [21]:
# only select read count that has sgRNA sequences data from refined library
read_count = read_count[read_count['spacer'].isin(library["spacer"])]
read_count

,sgRNA,spacer,GENE,RPE1_T0,RPE1_T3A_CTRL_LOPRIMER,RPE1_T3A_CTRL,RPE1_T3A_ENTI_LOPRIMER,RPE1_T3A_ENTI,RPE1_T3A_GEMC,RPE1_T3A_VINC,RPE1_T3B_CTRL,RPE1_T3B_ENTI,RPE1_T3B_GEMC,RPE1_T3B_VINC
0,A1BG_ACTGGCGCCATCGAGAGCCA,ACTGGCGCCATCGAGAGCCA,A1BG,164,83,93,33,50,105,39,44,118,33,77
1,A1BG_CAAGAGAAAGACCACGAGCA,CAAGAGAAAGACCACGAGCA,A1BG,492,416,288,275,262,277,286,222,401,216,228
2,A1BG_GCTCAGCTGGGTCCATCCTG,GCTCAGCTGGGTCCATCCTG,A1BG,258,54,49,38,25,101,28,5,57,52,32
3,A1BG_GTCGAGCTGATTCTGAGCGA,GTCGAGCTGATTCTGAGCGA,A1BG,487,668,360,462,307,353,278,290,565,193,209
4,A1CF_AGTTATGTTAGGTATACCCG,AGTTATGTTAGGTATACCCG,A1CF,149,242,133,193,187,165,133,140,379,87,189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71061,ZZEF1_GAGTGACAGACTCTTCGCCG,GAGTGACAGACTCTTCGCCG,ZZEF1,476,609,261,304,185,277,186,108,238,143,149
71062,ZZZ3_AAGAAGTAGAATCTCGACGC,AAGAAGTAGAATCTCGACGC,ZZZ3,78,31,20,29,26,17,12,12,7,2,13
71063,ZZZ3_AAGACCTTGAAAGTTTAGGC,AAGACCTTGAAAGTTTAGGC,ZZZ3,48,0,0,1,4,11,0,10,18,1,2
71064,ZZZ3_AGATGGTTCAGGTTCTCCGG,AGATGGTTCAGGTTCTCCGG,ZZZ3,261,144,76,99,72,105,45,66,172,66,61
71065,ZZZ3_GACCAATATACCCATAGCCT,GACCAATATACCCATAGCCT,ZZZ3,211,584,392,393,384,282,318,286,342,161,249

In [25]:
# remove the spacer column and export the file in a delimited format
# read_count.pop('spacer')
read_count.to_csv("../../data/sgrna_lfc_data/tkov3_data/refined_matrix-reads-by-gRNA-RPE1-drugZ.txt", sep = "\t", index = None)