### Normalize and correct sgRNA Log Fold Change data from DrugZ
#### adapted from Fortin et al, 2019
#### by Stefanus Bernard

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from function_to_normalize_sgrna_lfc import *

In [12]:
# import library data
library_data = pd.read_csv("../../CRISPR-KO-library-refinement-pipeline/public_crispr_library/tkov3_guide_sequence.tsv", sep ="\t", header = None)
library_data.columns = ['sgRNA', 'spacer', 'gene']
display(library_data.shape)

(71090, 3)

In [18]:
# function to process log fold change data from drugZ

def process_drugz_lfc(drugz_lfc):   
    lfc = pd.read_csv(drugz_lfc, sep ='\t')
    lfc = lfc.drop(columns=['GENE'])
    lfc = lfc.rename(columns={'Unnamed: 0':'sgRNA'})
    lfc[['gene', 'sgRNA']] = lfc['sgRNA'].str.split('_', n = 1, expand=True)
    lfc = lfc.drop(columns=['gene'])
    lfc = lfc.rename(columns={'sgRNA':'spacer'})

    # there are other columns such as: RPE1_T3A_CTRL, eb_std_0, zscore_fc_0, fc_0, RPE1_T3B_CTRL, eb_std_1, zscore_fc_1, fc_1
    lfc = lfc[['spacer', 'fc_0', 'fc_1']]
    return lfc

In [20]:
enti_lfc = process_drugz_lfc("./tkov3_data/ENTI_foldchange.txt")
enti_lfc = enti_lfc.rename(columns={'fc_0':'ENTI_A', 'fc_1':'ENTI_B'})
enti_lfc

                     spacer  ENTI_A  ENTI_B
0      GGTAGGCGAGTACTTGGGAG  -1.066   0.813
1      GCTTGGTACGCAGAGCACCG  -1.027  -0.261
2      AAAGATCTACTGCCCTCCTG  -0.420  -0.141
3      GAGAAGAGGACATTGCCCAG  -0.682  -0.444
4      ACCAGCAGCTCCTACACCGG   0.135   0.111
...                     ...     ...     ...
71085  TGTGGGTGCGCACTTCACCA   0.000  -0.241
71086  GAAGAGGCCATTGTCCAGAG   0.000  -1.765
71087  GTCGCCGGTCAAGTCGCCGG   1.442   0.880
71088  AGGTGGTTCAGTCCTTCACC   0.452   0.224
71089  GAAGCATGTCCAATTGCCAG   0.000   1.746

[71090 rows x 3 columns]

In [21]:
gemc_lfc = process_drugz_lfc("./tkov3_data/GEMC_foldchange.txt")
gemc_lfc = gemc_lfc.rename(columns={'fc_0':'GEMC_A', 'fc_1':'GEMC_B'})
gemc_lfc

                     spacer  GEMC_A  GEMC_B
0      GGTAGGCGAGTACTTGGGAG  -1.749   0.121
1      GCTTGGTACGCAGAGCACCG  -0.823  -0.439
2      AAAGATCTACTGCCCTCCTG  -0.944  -0.697
3      GAGAAGAGGACATTGCCCAG  -0.725  -0.751
4      ACCAGCAGCTCCTACACCGG   0.361   0.461
...                     ...     ...     ...
71085  TGTGGGTGCGCACTTCACCA   0.000   0.739
71086  GAAGAGGCCATTGTCCAGAG   0.000   0.042
71087  GTCGCCGGTCAAGTCGCCGG   0.413   0.722
71088  AGGTGGTTCAGTCCTTCACC   0.635   0.198
71089  GAAGCATGTCCAATTGCCAG   0.000   0.198

[71090 rows x 3 columns]

In [22]:
vinc_lfc = process_drugz_lfc("./tkov3_data/VINC_foldchange.txt")
vinc_lfc = vinc_lfc.rename(columns={'fc_0':'VINC_A', 'fc_1':'VINC_B'})
vinc_lfc

                     spacer  VINC_A  VINC_B
0      GGTAGGCGAGTACTTGGGAG  -2.472  -0.798
1      GCTTGGTACGCAGAGCACCG   0.297   0.873
2      AAAGATCTACTGCCCTCCTG   0.198   0.501
3      GAGAAGAGGACATTGCCCAG  -0.201  -0.176
4      ACCAGCAGCTCCTACACCGG   1.599   1.685
...                     ...     ...     ...
71085  TGTGGGTGCGCACTTCACCA   0.176   0.755
71086  GAAGAGGCCATTGTCCAGAG   0.000  -1.765
71087  GTCGCCGGTCAAGTCGCCGG   0.930  -0.400
71088  AGGTGGTTCAGTCCTTCACC   1.423   0.925
71089  GAAGCATGTCCAATTGCCAG   0.473   1.405

[71090 rows x 3 columns]

In [27]:
# Merge the three dataframes on 'spacer'
combined_lfc = enti_lfc.merge(gemc_lfc, on='spacer', how='outer')
combined_lfc = combined_lfc.merge(vinc_lfc, on='spacer', how='outer')

# Display the shape of the combined dataframe
print(f"Combined dataframe shape: {combined_lfc.shape}")

# Display the first few rows
combined_lfc

Combined dataframe shape: (71090, 7)

                     spacer  ENTI_A  ENTI_B  GEMC_A  GEMC_B  VINC_A  VINC_B
0      AAACAAACCACCGAAACCCT   0.539  -0.084  -0.090  -0.048  -0.417  -0.677
1      AAACAAACCTGGCTAAACGT   1.016  -0.745   0.098   0.659   0.575  -0.163
2      AAACAAACTGACAACCCTGA   0.855   0.346  -0.086   0.648   0.207   0.672
3      AAACAAAGTGGTGCTAAAGG  -0.304  -0.517  -0.997   0.475   0.023   0.410
4      AAACAAATGACACGGAGAGA   0.695  -0.176   0.844  -0.057   0.402  -0.089
...                     ...     ...     ...     ...     ...     ...     ...
71085  TTTGTTGGAATCTGATCCCA   0.486   0.680   0.344   0.765  -0.138   1.033
71086  TTTGTTGGAGAGATGTACGA   0.199  -0.091   0.404  -0.184   0.101  -0.040
71087  TTTGTTGGCACAAATACGGG   0.029   0.295  -0.210   0.684  -0.124   0.202
71088  TTTGTTGGCCACATCTACGG  -0.223  -0.571  -1.519  -0.230  -0.294  -0.246
71089  TTTGTTTGTAAGCACACCTG   0.022   0.495  -0.048   0.502  -0.073   0.152

[71090 rows x 7 columns]

In [28]:
combined_lfc = pd.merge(combined_lfc, library_data, how="left", on="spacer").set_index(['sgRNA', 'spacer', 'gene']).sort_values(by="sgRNA")
combined_lfc

,,,ENTI_A,ENTI_B,GEMC_A,GEMC_B,VINC_A,VINC_B
sgRNA,spacer,gene,,,,,,
sgA1BG_1,CAAGAGAAAGACCACGAGCA,A1BG,-0.064,-0.073,-0.132,-0.156,0.134,-0.055
sgA1BG_2,GCTCAGCTGGGTCCATCCTG,A1BG,-0.726,1.686,0.855,2.265,-0.540,1.687
sgA1BG_3,ACTGGCGCCATCGAGAGCCA,A1BG,-0.734,0.442,0.087,-0.458,-0.972,0.641
sgA1BG_4,GTCGAGCTGATTCTGAGCGA,A1BG,-0.156,0.033,-0.106,-0.689,-0.220,-0.553
sgA1CF_1,TGCGCTGGACCAGTGCGCGG,A1CF,-1.173,-0.427,-1.327,-1.162,-0.500,-0.868
...,...,...,...,...,...,...,...,...
sgluciferase_5,GCTATTCTGATTACACCCGA,luciferase,0.336,0.052,0.065,-0.744,0.902,-0.126
sgluciferase_6,ACGCTGGGCGTTAATCAGAG,luciferase,0.019,0.080,-0.033,-0.363,0.040,0.031
sgluciferase_7,GACCAACGCCTTGATTGACA,luciferase,0.548,0.027,0.376,0.252,0.393,-0.051
sgluciferase_8,CTATTCTGATTACACCCGAG,luciferase,0.092,0.444,-0.023,0.436,0.577,0.382
sgluciferase_9,TATTCTGATTACACCCGAGG,luciferase,-0.058,0.058,-0.236,0.183,-0.114,0.402

In [29]:
lfc_drugz = mean_row(combined_lfc)
lfc_drugz = lfc_drugz.reset_index()
lfc_drugz

                sgRNA                spacer        gene      mean
0            sgA1BG_1  CAAGAGAAAGACCACGAGCA        A1BG -0.057667
1            sgA1BG_2  GCTCAGCTGGGTCCATCCTG        A1BG  0.871167
2            sgA1BG_3  ACTGGCGCCATCGAGAGCCA        A1BG -0.165667
3            sgA1BG_4  GTCGAGCTGATTCTGAGCGA        A1BG -0.281833
4            sgA1CF_1  TGCGCTGGACCAGTGCGCGG        A1CF -0.909500
...               ...                   ...         ...       ...
71085  sgluciferase_5  GCTATTCTGATTACACCCGA  luciferase  0.080833
71086  sgluciferase_6  ACGCTGGGCGTTAATCAGAG  luciferase -0.037667
71087  sgluciferase_7  GACCAACGCCTTGATTGACA  luciferase  0.257500
71088  sgluciferase_8  CTATTCTGATTACACCCGAG  luciferase  0.318000
71089  sgluciferase_9  TATTCTGATTACACCCGAGG  luciferase  0.039167

[71090 rows x 4 columns]

In [31]:
lfc_drugz.to_csv("./output_normalized/tkov3_rpe1_lfc_drugz.csv", index=False)